--ASSIGNMENT_1_Retail Analysis
CREATE DATABASE ASSIGNMENT1

use ASSIGNMENT1

SELECT TOP 1 * FROM Customer
SELECT TOP 1 * FROM prod_cat_info
SELECT TOP 1 * FROM Transactions

--DATA PREPARATION AND UNDERSTANDING

--1. What is the total number of rows in each of the 3 tables in the database?
SELECT COUNT(*) as total_rows FROM Customer
UNION ALL
SELECT COUNT(*) as total_rows FROM prod_cat_info
UNION ALL
SELECT COUNT(*) as total_rows FROM Transactions

SELECT 
    (SELECT COUNT(*) FROM Customer) +
    (SELECT COUNT(*) FROM prod_cat_info) +
    (SELECT COUNT(*) FROM Transactions) AS total_rows;

--2. What is the total number of transactions that have a return?
SELECT COUNT(*) as total_returns
FROM Transactions
WHERE Qty < 0

--3.As you would have noticed, the dates provided across the datasets are not in a correct format.
--As first steps, pls convert the date variables into valid date formats before proceeding ahead.

SELECT *,
    FORMAT(CAST(DOB AS DATE), 'dd-MM-yyyy') AS dob_as_date
FROM Customer;


SELECT * ,
	FORMAT(CONVERT(DATETIME, tran_date,103),'dd-MM-yyyy') as tran_as_date
FROM Transactions

--4. What is the time range of the transaction data available for analysis? Show the output in number of days,
--months and years simultaneously in different columns.

SELECT 
MIN(tran_date) as start_date,
MAX(tran_date) as End_date,
DATEDIFF(DAY,MIN(tran_date),MAX(tran_date)) as total_days,
DATEDIFF(MONTH,MIN(tran_date),MAX(tran_date)) as total_months,
DATEDIFF(YEAR,MIN(tran_date),MAX(tran_date)) as total_year
from Transactions

--5. Which product category does the sub-category "DIY" belong to?

SELECT prod_cat 
FROM prod_cat_info
where prod_subcat = 'DIY'

--#######DATA ANALYSIS###########


--1. Which channel is most frequently used for transactions?

select top 1 Store_type,count(Store_type) as most_frequent_channel
from Transactions
group by Store_type
order by count(Store_type) DESC

--2. What is the count of Male and Female customers in the database?
SELECT Gender,COUNT(*) AS COUNT_Gender
FROM Customer
WHERE Gender IS NOT NULL
GROUP BY Gender

--3. From which city do we have the maximum number of customers and how many?
SELECT TOP 1  city_code , COUNT(customer_Id) AS customer_cnt
FROM Customer
GROUP BY city_code
ORDER BY  COUNT(customer_Id) DESC

--4. How many sub-categories are there under the Books category?
SELECT prod_cat,COUNT(prod_subcat) AS Cnt_subcategories
FROM prod_cat_info
GROUP BY prod_cat
HAVING prod_cat = 'Books'

--5. What is the maximum quantity of products ever ordered?
SELECT MAX(Qty) AS Max_Qty
FROM Transactions

--6. What is the net total revenue generated in categories Electronics and Books?
SELECT B.prod_cat, ROUND(SUM(A.total_amt),2) as total_revenue
FROM Transactions AS A
INNER JOIN prod_cat_info AS B
ON A.prod_cat_code = B.prod_cat_code AND A.prod_subcat_code = B.prod_sub_cat_code
WHERE B.prod_cat IN ('Electronics', 'Books')
group by B.prod_cat

--7. How many customers have > 10 transactions with us, excluding returns?
SELECT COUNT(customer_id)  AS CUST_CNT FROM (
	SELECT B.customer_Id
	FROM Transactions AS A
	JOIN Customer AS B
	on A.cust_id = B.customer_Id
	WHERE A.total_amt >  0
	GROUP BY B.customer_Id
	HAVING COUNT(transaction_id) > 10  ) AS T1

--8. What is the combined revenue earned from the "Electronics" & "Clothing" categories,
--from "Flagship stores"?
SELECT ROUND(SUM(CAST(A.total_amt AS FLOAT)),2) AS Combined_revenue
FROM Transactions AS A
JOIN prod_cat_info AS B
ON A.prod_cat_code = B.prod_cat_code AND A.prod_subcat_code = B.prod_sub_cat_code
WHERE B.prod_cat IN('Electronics', 'Clothing') AND A.Store_type LIKE 'Flagship%'

--9. What is the total revenue generated from "Male" customers in "Electronics" category? 
--Output should display total revenue by prod sub-cat.
SELECT C.prod_subcat,ROUND(SUM(B.total_amt),2) AS Total_Revenue
FROM Customer AS A
LEFT JOIN Transactions AS B
ON A.customer_Id = B.cust_id
LEFT JOIN prod_cat_info AS C
ON B.prod_cat_code= C.prod_cat_code AND B.prod_subcat_code  = C.prod_sub_cat_code
WHERE C.prod_cat = 'Electronics'
AND A.Gender = 'M'
group by C.prod_subcat

--10. What is percentage of sales and returns by product sub category; display onlY
--Top 5 sub categories in terms of sales?
SELECT TOP 5 B.prod_subcat, 
(SUM(A.TOTAL_AMT) * 100.0 / (SELECT SUM(TOTAL_AMT) FROM Transactions)) AS PERCENTAGE_OF_SALES, 
(SUM(CASE WHEN A.QTY < 0 THEN A.QTY ELSE 0 END) * -100.0 / SUM(A.QTY)) AS PERCENTAGE_OF_RETURN
FROM Transactions AS A
INNER JOIN prod_cat_info AS B
ON A.prod_cat_code = B.prod_cat_code 
AND A.prod_subcat_code = B.prod_sub_cat_code
GROUP BY B.prod_subcat
ORDER BY SUM(A.TOTAL_AMT) DESC;


--11. For all customers aged between 25 to 35 years find what is the net total revenue generated by 
--these consumers in last 30 days of transactions from max transaction date available in the data?
SELECT round(sum(cast(total_amt as float)),2) as Total_Revenue
FROM Customer AS A
JOIN Transactions AS B
ON A.customer_Id = B.cust_id
WHERE DATEDIFF(YEAR,DOB, (SELECT MAX(tran_date) AS d FROM Transactions) )
between 25 and 35 AND
DATEDIFF(DAY, B.tran_date, (SELECT MAX(tran_date) FROM Transactions)) <= 30


--12. Which product category has seen the max value of returns in the last 3 months of transactions?
SELECT TOP 1 B.prod_cat, SUM(A.total_amt) AS MAX_RETURNS
FROM Transactions AS A
JOIN prod_cat_info AS B
 ON A.prod_cat_code = B.prod_cat_code AND A.prod_subcat_code = B.prod_sub_cat_code
WHERE A.total_amt < 0
 AND A.tran_date  > DATEADD(MONTH, -3, (SELECT MAX(tran_date ) FROM Transactions))
GROUP BY B.prod_cat
ORDER BY MAX_RETURNS

--14. What are the categories for which average revenue is above the overall average. 

SELECT B.prod_cat ,AVG(A.total_amt) as Avg_Revenue
FROM Transactions AS A
JOIN prod_cat_info AS B
ON A.prod_cat_code = B.prod_cat_code AND A.prod_subcat_code = B.prod_sub_cat_code
GROUP BY B.prod_cat
HAVING AVG(A.total_amt) > (select Avg(total_amt) from Transactions)

--15. Find the average and total revenue by each subcategory for the categories
--which are among top 5 categories in terms of quantity sold.
SELECT B.prod_subcat, 
ROUND(AVG(A.total_amt),2) AS Avg_revenue,
ROUND(SUM(A.total_amt),2) AS Total_revenue
FROM Transactions AS A
JOIN prod_cat_info AS B
ON A.prod_cat_code = B.prod_cat_code AND A.prod_subcat_code = B.prod_sub_cat_code
WHERE B.prod_cat_code IN (SELECT prod_cat_code from
				(SELECT TOP 5 prod_cat_code ,SUM(QTY) AS Qty_sold
				FROM Transactions AS A
				group by prod_cat_code
				ORDER BY Qty_sold DESC ) AS T1)
GROUP BY B.prod_subcat
